"""add table_transactions

Revision ID: 3109278edce2
Revises: c05b8c9e06e4
Create Date: 2026-04-20 23:44:14.051827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3109278edce2'
down_revision: Union[str, Sequence[str], None] = 'c05b8c9e06e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_transacoes',
    sa.Column('id_transacao', sa.Integer(), nullable=False),
    sa.Column('conta_transmissora', sa.Integer(), nullable=False),
    sa.Column('conta_destino', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo_trasacao', sa.Enum('deposito', 'saque', 'transacao', name='transactiontype'), nullable=False),
    sa.Column('forma_pagamento', sa.Enum('debito', 'credito', 'dinheiro', 'pix', name='paymenttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conta_transmissora'], ['table_conta.id_conta'], ),
    sa.PrimaryKeyConstraint('id_transacao')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_transacoes')
    # ### end Alembic commands ###
