"""remove contranct unique on table_conta.agencia_conta

Revision ID: 4d53f75112f3
Revises: 657438d8095e
Create Date: 2026-04-29 22:31:14.937837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d53f75112f3'
down_revision: Union[str, Sequence[str], None] = '657438d8095e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('table_conta_agencia_conta_key'), 'table_conta', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('table_conta_agencia_conta_key'), 'table_conta', ['agencia_conta'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
