"""add table_conta

Revision ID: c05b8c9e06e4
Revises: 87aa5a46a36f
Create Date: 2026-04-19 00:16:11.785976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c05b8c9e06e4'
down_revision: Union[str, Sequence[str], None] = '87aa5a46a36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_conta',
    sa.Column('id_conta', sa.Integer(), nullable=False),
    sa.Column('agencia_conta', sa.Integer(), nullable=False),
    sa.Column('banco_id', sa.Integer(), nullable=False),
    sa.Column('user_cpf', sa.String(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['banco_id'], ['table_banco.id_bank'], ),
    sa.ForeignKeyConstraint(['user_cpf'], ['table_user.user_cpf'], ),
    sa.PrimaryKeyConstraint('id_conta'),
    sa.UniqueConstraint('agencia_conta')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_conta')
    # ### end Alembic commands ###
