name: pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      ALGORITHIM: ${{ secrets.ALGORITHIM }}
      ACCESS_TOKEN_EXPIRE_MINUTS: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTS }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:

      - name: Copiar os arquivos 
        uses: actions/checkout@v4

      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Instalar o poetry
        run: pipx install poetry

      - name: Instalar dependências
        run: poetry install --no-root

      - name: Executar os testes
        run: poetry run task test